export const allProjects = [
    {
        type: "software",
        name: "Fibonnaci Fractal Visualizer",
        shortDescription: "Algorithm that visualizes Fibonacci fractals up to n=35... if your computer has enough memory 😉",
        longDescription: "One of the games I spent hours on and could never get the best score, so I decided to recreate it and train a neural network to do it for me!",
        languages: ["C", "Bash"],
        githubLink: "https://github.com/lukamircetic/PathfindingVisualizer",
        demoLink: "https://lukamircetic.github.io/PathfindingVisualizer/",
    },
    {
        type: "biomedical",
        name: "Native Stem",
        shortDescription: "Designed and built an artificial hip implant for a patient with right hip dysplasia.",
        longDescription: "Designed and built an artificial hip implant for a patient with right hip dysplasia.",
        languages: ["C++", "AutoCAD", "3D Printing"],
        githubLink: "",
        demoLink: "https://lukamircetic.ca/static/media/dp2.6dd03822.pdf",
    },
    {
        type: "biomedical",
        name: "The Reverb",
        shortDescription: "Designed and built a medical device that alerts a user if they have been listening to music too loud.",
        longDescription: "Designed and built a medical device that alerts a user if they have been listening to music too loud.",
        languages: ["Python", "AutoCAD", "3D Printing", "RaspberryPi"],
        githubLink: "",
        demoLink: "https://lukamircetic.ca/static/media/dp3.4291d560.pdf",
    },
    {
        type: "software",
        name: "Flies AI",
        shortDescription: "Neural network that trains flies to find their way to a target through reinforcement learning",
        longDescription: "One of the games I spent hours on and could never get the best score, so I decided to recreate it and train a neural network to do it for me!",
        languages: ["Java", "Processing"],
        githubLink: "https://github.com/lukamircetic/Flies",
        demoLink: "",
    },
    {
        type: "biomedical",
        name: "Sensitouch",
        shortDescription: "Designed an elevator attachment that makes it more accessible for people with disabilities to press elevator buttons.",
        longDescription: "Designed and built a medical device that alerts a user if they have been listening to music too loud.",
        languages: ["AutoCAD", "3D Printing"],
        githubLink: "",
        demoLink: "https://lukamircetic.ca/static/media/dp3.4291d560.pdf",
    },
    {
        type: "biomedical",
        name: "Auto C.A.D.",
        shortDescription: "Genetically engineered a bacteria to dissolve arterial plaque using lab techniques such as PCR and DNA purification",
        longDescription: "Designed and built a medical device that alerts a user if they have been listening to music too loud",
        languages: ["Matlab", "Genome Compiler"],
        githubLink: "",
        demoLink: "https://lukamircetic.ca/static/media/dpy2.5443ea2c.pdf",
    },        
    {
        type: "biomedical",
        name: "Ostomy Bag Solution",
        shortDescription: "Designed a low profile medical device, which is an extension of modern ostomy bags for night use",
        longDescription: "Designed and built a medical device that alerts a user if they have been listening to music too loud",
        languages: ["AutoCAD", "3D Printing"],
        githubLink: "",
        demoLink: "https://lukamircetic.ca/static/media/dp3.4291d560.pdf",
    },
    {
        type: "software",
        name: "Calendar To-Do",
        shortDescription: "Full stack application which organizes your to-do lists by date.",
        longDescription: "Google Keep and Google Calendar were missing something, so I combined them! Full stack application which organizes your to-do lists by date.",
        languages: ["Svelte", "Node.js", "Express", "MongoDB", "Heroku"],
        githubLink: "https://github.com/lukamircetic/Calendar-ToDo",
        demoLink: "https://calendar-todo-luka.herokuapp.com/",
    },
    {
        type: "software",
        name: "Flappy Bird ML",
        shortDescription: "Flappy bird game, with a neural network training in real-time.",
        longDescription: "One of the games I spent hours on and could never get the best score, so I decided to recreate it and train a neural network to do it for me!",
        languages: ["Processing.js", "Tensorflow.js"],
        githubLink: "https://github.com/lukamircetic/flappybirdneuralnet",
        demoLink: "https://lukamircetic.github.io/flappybirdneuralnet/",
    },
];

